/**
 * Shared type definitions used by both the frontend and the server.
 *
 * Design principles:
 *  - WikiProject never exposes OS-level absolute paths to the frontend.
 *    The server maintains a registry mapping projectId → absolutePath.
 *  - FileNode uses relativePath (relative to project root) so the frontend
 *    never constructs or stores absolute filesystem paths.
 */

export interface WikiProject {
  id: string    // Stable UUID generated by the server
  name: string  // Human-readable display name
}

export interface FileNode {
  name: string
  relativePath: string  // Relative to the project root (e.g. "wiki/page.md")
  is_dir: boolean
  children?: FileNode[]
}

export interface WikiPage {
  relativePath: string
  content: string
  frontmatter: Record<string, unknown>
}

/** Result of browsing the server's filesystem for project parent directories. */
export interface BrowseResult {
  path: string
  dirs: string[]
  files: string[]
}

export interface LlmConfig {
  provider: "openai" | "anthropic" | "google" | "ollama" | "custom" | "minimax" | "wps"
  apiKey: string
  model: string
  ollamaUrl: string
  customEndpoint: string
  maxContextSize: number
}

export interface SearchApiConfig {
  provider: "tavily" | "none"
  apiKey: string
}

export interface EmbeddingConfig {
  enabled: boolean
  endpoint: string
  apiKey: string
  model: string
}

export interface ServerIngestTask {
  id: string
  projectId: string
  sourcePath: string   // relative to project root
  folderContext: string
  status: "pending" | "running" | "done" | "error"
  detail: string
  filesWritten: string[]
  error: string | null
  createdAt: number
  updatedAt: number
}
