/**
 * Pure validation and frontmatter utilities for wiki pages generated by LLM.
 * These functions act as the quality gates before any content reaches disk.
 */

import path from "node:path"

// ── Frontmatter helpers ────────────────────────────────────────────────────

export function extractFmField(content: string, field: string): string {
  const m = content.match(new RegExp(`^${field}:\\s*["']?([^"'\\n]+?)["']?\\s*$`, "m"))
  return m ? m[1].trim() : ""
}

export function extractMarkdownBody(content: string): string {
  const fmMatch = content.match(/^---\s*\n[\s\S]*?\n---\s*\n?/)
  if (fmMatch) return content.slice(fmMatch[0].length).trim()
  return content.trim()
}

export function normalizeForMatch(text: string): string {
  return text.toLowerCase().replace(/\s+/g, "").replace(/[`*_[\]()#.:,，。！？!?\-]/g, "")
}

export function extractFirstHeading(body: string): string {
  const m = body.match(/^#\s+(.+)\s*$/m)
  return m ? m[1].trim() : ""
}

/**
 * Ensure a markdown string has a proper --- fenced frontmatter block.
 * If the content starts with bare key: value pairs, wraps them in --- delimiters.
 */
export function normFrontmatter(content: string): string {
  if (/^-{3}[ \t]*\r?\n/.test(content)) return content
  const m = content.match(/^((?:[a-z_][a-z0-9_]*[ \t]*:[ \t]*[^\n]*\n){2,})/)
  if (m) {
    return `---\n${m[1]}---\n\n${content.slice(m[1].length).replace(/^\n+/, "")}`
  }
  return content
}

/**
 * Set or insert a frontmatter key/value pair (inside the --- block).
 */
export function setFmField(fm: string, key: string, value: string): string {
  const line = `${key}: ${value}`
  const re = new RegExp(`^${key}:\\s*.*$`, "m")
  if (re.test(fm)) return fm.replace(re, line)
  return `${fm}\n${line}`.trim()
}

/**
 * Correct the `title` and `type` frontmatter fields to match the canonical
 * values derived from the file path. Called by writeSingleBlock so that LLM
 * output with wrong titles never reaches disk.
 */
export function ensureCanonicalTitleType(rel: string, content: string): string {
  const fmMatch = content.match(/^(---\n)([\s\S]*?)(\n---\n?)([\s\S]*)$/)
  if (!fmMatch) return content

  const canonicalType = rel === "wiki/overview.md"
    ? "overview"
    : rel.includes("/entities/") ? "entity"
    : rel.includes("/concepts/") ? "concept"
    : /^wiki\/sources\/[^/]+\.md$/.test(rel) ? "source"
    : null

  const entityMatch = rel.match(/^wiki\/sources\/.+\/(entities|concepts)\/([^/]+)\.md$/)
  const sourceMatch = rel.match(/^wiki\/sources\/([^/]+)\.md$/)
  const canonicalTitle = rel === "wiki/overview.md"
    ? "Wiki 总览"
    : entityMatch ? path.basename(rel, ".md")
    : sourceMatch ? sourceMatch[1]
    : null

  if (!canonicalType && !canonicalTitle) return content

  let fm = fmMatch[2]
  if (canonicalType) fm = setFmField(fm, "type", canonicalType)
  if (canonicalTitle) fm = setFmField(fm, "title", canonicalTitle)
  return `---\n${fm}\n---\n${fmMatch[4]}`
}

/**
 * Check that the frontmatter title in a wiki file matches the file's basename.
 * Returns true when consistent (or when the check is not applicable).
 * This is the invariant that prevents LLM path-content mismatches from reaching disk.
 */
export function isTitleFilenameConsistent(rel: string, content: string): boolean {
  const titleMatch = content.match(/^---\s*\n[\s\S]*?^title:\s*(.+?)\s*$/m)
  const titleInFrontmatter = titleMatch?.[1]?.trim()
  if (!titleInFrontmatter) return true // no title → let empty-content check handle it

  // 汇总页：wiki/sources/<base>.md（直接在 sources/ 下，不含子目录）
  const sourceSummaryMatch = rel.match(/^wiki\/sources\/([^/]+)\.md$/)
  if (sourceSummaryMatch) {
    return titleInFrontmatter.toLowerCase() === sourceSummaryMatch[1].toLowerCase()
  }

  // 实体/概念页：wiki/sources/<base>/entities/<name>.md 或 .../concepts/<name>.md
  if (!rel.match(/\/(entities|concepts)\/[^/]+\.md$/)) return true
  const fileBasename = path.basename(rel, ".md")
  return titleInFrontmatter.toLowerCase() === fileBasename.toLowerCase()
}

/**
 * Check semantic consistency between path/title/body for generated pages.
 * This blocks cases where filename/title are valid but body obviously belongs to another topic.
 */
export function isBodyTitleSemanticallyConsistent(rel: string, content: string): boolean {
  if (!rel.endsWith(".md")) return true
  if (rel === "wiki/log.md" || rel === "wiki/index.md" || rel === "wiki/overview.md") return true
  const titleMatch = content.match(/^---\s*\n[\s\S]*?^title:\s*(.+?)\s*$/m)
  const title = titleMatch?.[1]?.trim()
  if (!title) return true

  const expectedType = rel.includes("/entities/")
    ? "entity"
    : rel.includes("/concepts/")
      ? "concept"
      : null
  if (expectedType) {
    const type = extractFmField(content, "type")
    if (type && type !== expectedType) return false
  }

  const body = extractMarkdownBody(content)
  if (!body) return false
  const titleNorm = normalizeForMatch(title)
  const bodyNorm = normalizeForMatch(body)
  const heading = extractFirstHeading(body)
  if (heading) {
    const headingNorm = normalizeForMatch(heading)
    if (!headingNorm.includes(titleNorm) && !titleNorm.includes(headingNorm)) return false
  }

  if (rel.includes("/entities/") || rel.includes("/concepts/")) {
    const hasDirectMention = bodyNorm.includes(titleNorm)
    const hasWikilinkMention = body.includes(`[[${title}]]`)
    if (!hasDirectMention && !hasWikilinkMention) return false
  }

  const summaryMatch = rel.match(/^wiki\/sources\/([^/]+)\.md$/)
  if (summaryMatch) {
    const sourceBaseNorm = normalizeForMatch(summaryMatch[1])
    const hasSourceMention = bodyNorm.includes(sourceBaseNorm) || body.includes(`[[${summaryMatch[1]}]]`)
    if (!hasSourceMention) return false
  }

  return true
}
