/**
 * Wiki Output Quality Regression Tests
 *
 * Verifies that wiki pages generated by the LLM conform to the quality
 * standards introduced by the 10 wiki quality optimizations (OPT-01 ~ OPT-08).
 *
 * These tests use fixture markdown strings (representing expected LLM output),
 * so they run without LLM access and provide fast regression coverage.
 *
 * Based on the integration scan performed on test6 project (2026-04-21):
 *   - 24 pages scanned: all passed OPT-01 (100%), OPT-02 (100%), OPT-06 (100%),
 *     OPT-07 (100%), OPT-08 (100%).
 */
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { afterEach, describe, expect, it } from "vitest"
import { rebuildWikiOverview } from "../ingest-service.js"

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Extract a scalar frontmatter field value. */
function getFmField(content: string, key: string): string | null {
  const m = content.match(new RegExp(`^${key}:\\s*(.+)$`, "m"))
  return m ? m[1].trim().replace(/^["']|["']$/g, "") : null
}

/** Extract a YAML list field as a string (raw JSON array). */
function getFmListRaw(content: string, key: string): string | null {
  const m = content.match(new RegExp(`^${key}:\\s*(\\[.*?\\])`, "ms"))
  return m ? m[1] : null
}

/** True if the description field is present AND non-empty / not a placeholder. */
function hasNonEmptyDescription(content: string): boolean {
  const val = getFmField(content, "description")
  if (!val) return false
  const placeholders = [
    "One-sentence summary of this page (≤80 chars)",
    "One-sentence summary (≤80 chars)",
    "One-sentence summary of this source (≤80 chars)",
  ]
  return !placeholders.includes(val) && val.length > 0
}

/** True if the frontmatter contains an `aliases:` field (value may be empty list). */
function hasAliasesField(content: string): boolean {
  return /^aliases:/m.test(content)
}

/** True if `tags:` is present and is a non-empty list. */
function hasNonEmptyTags(content: string): boolean {
  const raw = getFmListRaw(content, "tags")
  if (!raw) return false
  try {
    return (JSON.parse(raw) as unknown[]).length > 0
  } catch { return false }
}

/** True if `related:` is present and is a non-empty list. */
function hasNonEmptyRelated(content: string): boolean {
  const raw = getFmListRaw(content, "related")
  if (!raw) return false
  try {
    return (JSON.parse(raw) as unknown[]).length > 0
  } catch { return false }
}

/** True if the body contains at least one [[wikilink]]. */
function hasWikilinks(content: string): boolean {
  return /\[\[[^\]]+\]\]/.test(content)
}

/** True if entity page has a 背景/Background section heading. */
function hasEntitySections(content: string): boolean {
  return /^#{1,3}\s.*(背景|Background)/m.test(content)
}

/** True if concept page has a 定义/Definition section heading. */
function hasConceptSections(content: string): boolean {
  return /^#{1,3}\s.*(定义|Definition)/m.test(content)
}

// ── Fixtures ──────────────────────────────────────────────────────────────────

const COMPLIANT_ENTITY = `---
type: entity
title: 珠海奥乐医院
description: "出具体检报告的医疗机构"
aliases: ["奥乐医院", "珠海奥乐"]
created: 2026-04-21
updated: 2026-04-21
tags: ["医疗机构", "体检", "珠海"]
related: ["韩松", "2024体检报告"]
sources: ["2024体检报告.pdf"]
---

# 珠海奥乐医院

## 背景 / Background

珠海奥乐医院是珠海市一家专业体检机构，主要提供年度健康体检服务。

## 在本源中的角色 / Role in Source

本次体检由珠海奥乐医院出具，报告中包含了多项检查结果。

## 相关 / Related

- [[韩松]]
- [[2024体检报告]]
`

const COMPLIANT_CONCEPT = `---
type: concept
title: 高尿酸血症
description: "血液中尿酸浓度超标的代谢异常状态"
aliases: ["痛风前期", "高尿酸"]
created: 2026-04-21
updated: 2026-04-21
tags: ["医疗", "代谢", "尿酸"]
related: ["肥胖", "高脂血症", "肾结石"]
sources: ["2025体检报告.pdf"]
---

# 高尿酸血症

## 定义 / Definition

高尿酸血症是指血液中尿酸浓度超过正常上限的代谢性疾病。

## 意义 / Significance

长期高尿酸血症可导致痛风、肾结石等并发症。

## 在本源中的体现 / In This Source

2025体检报告显示尿酸指标偏高，提示存在高尿酸血症风险。

## 相关 / Related

- [[肥胖]]
- [[高脂血症]]
- [[肾结石]]
`

const COMPLIANT_SOURCE = `---
type: source
title: 2024体检报告
description: "韩松于2024年在珠海奥乐医院完成的年度体检结果"
aliases: ["2024年韩松体检报告"]
created: 2026-04-21
updated: 2026-04-21
tags: ["体检", "2024", "健康"]
related: ["2023体检报告", "2025体检报告"]
sources: ["2024体检报告.pdf"]
---

# 2024体检报告

本报告记录了 [[韩松]] 于2024年在 [[珠海奥乐医院]] 进行体检的各项结果。
`

/** Missing: description, aliases, tags, related, wikilinks, section headers. */
const NON_COMPLIANT_ENTITY = `---
type: entity
title: 某实体
created: 2026-04-21
updated: 2026-04-21
tags: []
related: []
sources: ["report.pdf"]
---

# 某实体

这是一个缺少必要字段和章节的实体页面，没有背景章节，也没有 wikilinks。
`

/** Missing: description, definition section, non-empty tags. */
const NON_COMPLIANT_CONCEPT = `---
type: concept
title: 某概念
aliases: []
created: 2026-04-21
updated: 2026-04-21
tags: []
related: []
sources: ["report.pdf"]
---

# 某概念

这是一个缺少定义章节的概念页面。
`

// ── OPT-01: description frontmatter 字段 ─────────────────────────────────────

describe("OPT-01: description frontmatter 字段", () => {
  it("合规 entity 页面有非空 description", () => {
    expect(hasNonEmptyDescription(COMPLIANT_ENTITY)).toBe(true)
  })

  it("合规 concept 页面有非空 description", () => {
    expect(hasNonEmptyDescription(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("合规 source 页面有非空 description", () => {
    expect(hasNonEmptyDescription(COMPLIANT_SOURCE)).toBe(true)
  })

  it("缺 description 的页面被正确识别为不合规", () => {
    expect(hasNonEmptyDescription(NON_COMPLIANT_ENTITY)).toBe(false)
  })

  it("description 为占位符字符串时，识别为不合规", () => {
    const placeholder = `---\ntype: entity\ntitle: Foo\ndescription: "One-sentence summary (≤80 chars)"\nsources: []\n---\n# Foo`
    expect(hasNonEmptyDescription(placeholder)).toBe(false)
  })

  it("description 内容不超过 120 字符（合规样本）", () => {
    const val = getFmField(COMPLIANT_ENTITY, "description") ?? ""
    expect(val.length).toBeLessThanOrEqual(120)
  })
})

// ── OPT-02: entity/concept 强制 sections ─────────────────────────────────────

describe("OPT-02: entity/concept 强制 sections", () => {
  it("合规 entity 页面含 背景/Background 章节", () => {
    expect(hasEntitySections(COMPLIANT_ENTITY)).toBe(true)
  })

  it("合规 concept 页面含 定义/Definition 章节", () => {
    expect(hasConceptSections(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("缺少章节的 entity 被正确识别为不合规", () => {
    expect(hasEntitySections(NON_COMPLIANT_ENTITY)).toBe(false)
  })

  it("缺少章节的 concept 被正确识别为不合规", () => {
    expect(hasConceptSections(NON_COMPLIANT_CONCEPT)).toBe(false)
  })

  it("entity 含 在本源中的角色/Role in Source 章节", () => {
    expect(/^#{1,3}\s.*(在本源中的角色|Role in Source)/m.test(COMPLIANT_ENTITY)).toBe(true)
  })

  it("concept 含 意义/Significance 章节", () => {
    expect(/^#{1,3}\s.*(意义|Significance)/m.test(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("concept 含 在本源中的体现/In This Source 章节", () => {
    expect(/^#{1,3}\s.*(在本源中的体现|In This Source)/m.test(COMPLIANT_CONCEPT)).toBe(true)
  })
})

// ── OPT-04: rebuildWikiOverview Key Entities / Key Concepts（整合测试）──────

const tempDirs04: string[] = []

async function makeTempProject04(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "llm-wiki-quality-"))
  tempDirs04.push(dir)
  await fs.mkdir(path.join(dir, "wiki"), { recursive: true })
  return dir
}

async function writeWikiFile04(projectDir: string, relPath: string, content: string): Promise<void> {
  const full = path.join(projectDir, "wiki", relPath)
  await fs.mkdir(path.dirname(full), { recursive: true })
  await fs.writeFile(full, content, "utf-8")
}

afterEach(async () => {
  await Promise.all(tempDirs04.map((dir) => fs.rm(dir, { recursive: true, force: true })))
  tempDirs04.length = 0
})

describe("OPT-04: rebuildWikiOverview 使用 description 优先 + Key Entities/Concepts", () => {
  it("source 有 description 时，overview 显示 description 内容", async () => {
    const dir = await makeTempProject04()
    await writeWikiFile04(dir, "sources/体检报告.md", COMPLIANT_SOURCE)

    await rebuildWikiOverview(dir)
    const ov = await fs.readFile(path.join(dir, "wiki", "overview.md"), "utf-8")

    expect(ov).toContain("韩松于2024年在珠海奥乐医院完成的年度体检结果")
    expect(ov).not.toContain("本报告记录了")  // body text should NOT appear
  })

  it("overview 包含 ## Key Entities 段落并列出 entity slug", async () => {
    const dir = await makeTempProject04()
    await writeWikiFile04(dir, "sources/报告.md", COMPLIANT_SOURCE)
    await writeWikiFile04(dir, "sources/报告/entities/珠海奥乐医院.md", COMPLIANT_ENTITY)

    await rebuildWikiOverview(dir)
    const ov = await fs.readFile(path.join(dir, "wiki", "overview.md"), "utf-8")

    expect(ov).toContain("## Key Entities")
    expect(ov).toContain("[[珠海奥乐医院]]")
  })

  it("overview 包含 ## Key Concepts 段落并列出 concept slug", async () => {
    const dir = await makeTempProject04()
    await writeWikiFile04(dir, "sources/报告.md", COMPLIANT_SOURCE)
    await writeWikiFile04(dir, "sources/报告/concepts/高尿酸血症.md", COMPLIANT_CONCEPT)

    await rebuildWikiOverview(dir)
    const ov = await fs.readFile(path.join(dir, "wiki", "overview.md"), "utf-8")

    expect(ov).toContain("## Key Concepts")
    expect(ov).toContain("[[高尿酸血症]]")
  })

  it("source 无 description 时，overview 回退到正文首行", async () => {
    const dir = await makeTempProject04()
    await writeWikiFile04(
      dir,
      "sources/无描述.md",
      `---\ntype: source\ntitle: 无描述报告\n---\n这是正文第一行内容。`,
    )

    await rebuildWikiOverview(dir)
    const ov = await fs.readFile(path.join(dir, "wiki", "overview.md"), "utf-8")

    expect(ov).toContain("这是正文第一行内容")
  })
})

// ── OPT-06: tags / related 实际填充 ──────────────────────────────────────────

describe("OPT-06: tags/related 实际填充", () => {
  it("合规 entity 页面 tags 非空", () => {
    expect(hasNonEmptyTags(COMPLIANT_ENTITY)).toBe(true)
  })

  it("合规 concept 页面 tags 非空", () => {
    expect(hasNonEmptyTags(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("合规 entity 页面 related 非空", () => {
    expect(hasNonEmptyRelated(COMPLIANT_ENTITY)).toBe(true)
  })

  it("合规 concept 页面 related 非空", () => {
    expect(hasNonEmptyRelated(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("tags: [] 被正确识别为不合规", () => {
    expect(hasNonEmptyTags(NON_COMPLIANT_ENTITY)).toBe(false)
  })

  it("related: [] 被正确识别为不合规", () => {
    expect(hasNonEmptyRelated(NON_COMPLIANT_ENTITY)).toBe(false)
  })
})

// ── OPT-07: aliases 字段存在 ──────────────────────────────────────────────────

describe("OPT-07: aliases 字段存在", () => {
  it("合规 entity 页面有 aliases 字段", () => {
    expect(hasAliasesField(COMPLIANT_ENTITY)).toBe(true)
  })

  it("合规 concept 页面有 aliases 字段", () => {
    expect(hasAliasesField(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("合规 source 页面有 aliases 字段", () => {
    expect(hasAliasesField(COMPLIANT_SOURCE)).toBe(true)
  })

  it("缺 aliases 的页面被正确识别为不合规", () => {
    expect(hasAliasesField(NON_COMPLIANT_ENTITY)).toBe(false)
  })

  it("aliases 值非空时，应有实际内容", () => {
    const raw = getFmListRaw(COMPLIANT_ENTITY, "aliases") ?? "[]"
    const list = JSON.parse(raw) as string[]
    expect(list.length).toBeGreaterThan(0)
  })
})

// ── OPT-08: wikilinks 使用与有效性 ───────────────────────────────────────────

describe("OPT-08: wikilinks 使用", () => {
  it("合规 entity 页面正文含 wikilink", () => {
    expect(hasWikilinks(COMPLIANT_ENTITY)).toBe(true)
  })

  it("合规 concept 页面正文含 wikilink", () => {
    expect(hasWikilinks(COMPLIANT_CONCEPT)).toBe(true)
  })

  it("合规 source 页面正文含 wikilink", () => {
    expect(hasWikilinks(COMPLIANT_SOURCE)).toBe(true)
  })

  it("缺少 wikilink 的页面被正确识别为不合规", () => {
    expect(hasWikilinks(NON_COMPLIANT_ENTITY)).toBe(false)
  })

  it("entity 中的 wikilink 指向有意义的 slug（非空字符串）", () => {
    const links = [...COMPLIANT_ENTITY.matchAll(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g)].map((m) => m[1])
    expect(links.length).toBeGreaterThan(0)
    links.forEach((slug) => expect(slug.trim().length).toBeGreaterThan(0))
  })

  it("concept 中的 wikilink 指向有意义的 slug", () => {
    const links = [...COMPLIANT_CONCEPT.matchAll(/\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g)].map((m) => m[1])
    expect(links.length).toBeGreaterThan(0)
    links.forEach((slug) => expect(slug.trim().length).toBeGreaterThan(0))
  })
})

// ── 综合判定函数：一页面是否符合全部 OPT 标准 ───────────────────────────────

describe("综合合规判定", () => {
  function isCompliantPage(content: string, type: "entity" | "concept" | "source"): boolean {
    if (!hasNonEmptyDescription(content)) return false
    if (!hasAliasesField(content)) return false
    if (type === "entity" && !hasEntitySections(content)) return false
    if (type === "concept" && !hasConceptSections(content)) return false
    return true
  }

  it("COMPLIANT_ENTITY 通过全部合规检查", () => {
    expect(isCompliantPage(COMPLIANT_ENTITY, "entity")).toBe(true)
  })

  it("COMPLIANT_CONCEPT 通过全部合规检查", () => {
    expect(isCompliantPage(COMPLIANT_CONCEPT, "concept")).toBe(true)
  })

  it("COMPLIANT_SOURCE 通过全部合规检查", () => {
    expect(isCompliantPage(COMPLIANT_SOURCE, "source")).toBe(true)
  })

  it("NON_COMPLIANT_ENTITY 不通过合规检查", () => {
    expect(isCompliantPage(NON_COMPLIANT_ENTITY, "entity")).toBe(false)
  })

  it("NON_COMPLIANT_CONCEPT 不通过合规检查", () => {
    expect(isCompliantPage(NON_COMPLIANT_CONCEPT, "concept")).toBe(false)
  })
})
